#+title: README
#+author: MondragonDevelopment

* Instructions to create a Vue project

For Vue 3 projects, Vite (pronounced “veet”) is the recommended build
tool due to its faster development server and streamlined
configuration.

- Install pnpm using the standalone script provided in their webpage.

- Install Node.js with the command: pn runtime set node lts -g
  
- Open Terminal or a command prompt and use Vite to create a new
  project: pn create vue@latest and if prompted to install any
  packages, enter y to proceed.

- Follow the prompts to choose your project name, preferred package
  manager, and additional features (e.g., TypeScript, testing
  framework). You can accept these defaults.

- Navigate to the project directory: cd my-vue-app

- Install dependencies using the pn install command. As you are new to
  pnpm, ignore any warnings or errors.

- Start the server by running the pn dev command. If your computer’s
  firewall asks for permissions, click Allow.

- Once the server has started, open your web browser and go to
  http://localhost:3000/ to view your Vue.js application.
